### ISSUE TITLE
service 테스트 시에 실제 db 에 저장이 되는지 확인을 하려면 어떻게 해야될까요?

### ISSUE THREAD

**Issue by zhtmr** [TodayWhatTodo/backend#19]
아래처럼 repository.findById() 해서 꺼내오는게 맞을까요?

<img width="814" alt="image" src="https://github.com/TodayWhatTodo/backend/assets/48509269/6998c7c8-6d76-40f9-b8b8-2eae83fed7f3">

**Comment by yudonggeun** [comment]
꺼내오는 것이 맞습니다.
