### ISSUE TITLE
Request, Response 클래스 이름에 대해서...

### ISSUE THREAD

**Issue by yudonggeun** [TodayWhatTodo/backend#36]
Request, Response 클래스 이름을 ...RequestDto, ...ResponseDto 이런 식으로 저희가 사용을 했지만 사용을 하면서 드는 의문이 있었습니다.

Dto 라는 이름이 과연 필요한가?

그래서 ...Request ...Response로 단순하게 이름을 변경하여 사용을 하는 것이 어떨까요?

**Comment by zhtmr** [comment]
저도 관례처럼 쓰긴했는데 dto가 빠져도 의미상으로 크게 상관 없을것 같긴 해요. 코딩 컨벤션이 어느쪽이 더 좋은건지는 잘 모르겠어요![image](https://github.com/TodayWhatTodo/backend/assets/48509269/4e6e5882-bbb4-49c4-a8c8-32a155870b17)

**Comment by yudonggeun** [comment]
잠시 찾아보니까 dto를 꼭 써야하는 규칙이 있는 것도 아니고 주어진 역할에 맞게 잘 사용하면 될 듯하다고 생각해요.

https://www.inflearn.com/questions/89727/%EC%9A%94%EC%B2%AD%EB%B0%9B%EB%8A%94-%EA%B0%9D%EC%B2%B4%EC%9D%98-%EC%9D%B4%EB%A6%84%EB%8F%84-dto%EB%A1%9C-%EB%84%A4%EC%9D%B4%EB%B0%8D-%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C%EC%9A%94

이 질문 답글을 보니까 저런식으로 필요한 상황에서 명확하게 나타내는 것이 저는 마음에 들어요.

**Comment by zhtmr** [comment]
저렇게 하는것도 괜찮아보이네요. 목적도 명확해 보이고

**Comment by yudonggeun** [comment]
그럼 저런 방식으로 한번 도입을 해볼께요
