### ISSUE TITLE
JpaAuditing 을 메인 메소드 말고 따로 설정파일로 빼놓는게 어떠신가요?

### ISSUE THREAD

**Issue by zhtmr** [TodayWhatTodo/backend#5]
<img width="683" alt="image" src="https://github.com/TodayWhatTodo/backend/assets/48509269/da5bf6ea-0978-4b42-b5b6-aaeac49a4a37">  
  
메인메소드 위에 @EnableJpaAuditing 이거를 JpaConfig 파일로 따로 빼는게 좋을거 같아요. 

---   

<img width="838" alt="image" src="https://github.com/TodayWhatTodo/backend/assets/48509269/2f2d2ebc-9e6d-414a-9095-14ddc7ec3c94">

<img width="767" alt="image" src="https://github.com/TodayWhatTodo/backend/assets/48509269/f45c2ccd-a01f-4d29-927a-ebc538337675">

상속받아서 사용

**Comment by yudonggeun** [comment]
1. jpa config 만들어서 관리하는 것도 무방할 것 같아요.
2. 기본 entity 만드신 것 잘 봤어요. 그런데 어제 같이 만든 erd에서 entity 생성일과 수정일 속성이 없는 경우도 있어서 고민을 해봐야할 듯해요. 저는 일단 분리해서 만들고 나중에 중복 여부가 심하게 느껴진다면 리펙토링하는 것은 어떨까요?

**Comment by zhtmr** [comment]
생성일 수정일 필드가 없는 엔티티의 경우에는 상속을 안받고 그대로 쓰면 될것같아요.

**Comment by zhtmr** [comment]
@WebMvcTest 로 컨트롤러 테스트 시에 @EnableJpaAuditing 이 메인메소드 클래스 위에 붙어있으면 엔티티도 필요해서 테스트하기 힘들다고 나오네요.

[링크](https://codingram.tistory.com/m/103)

**Comment by yudonggeun** [comment]
@WebMvcTest 보다는 @SpringBootTest 권장 드려요. 왜냐하면 webmvctest와 spring boot test 를 동시에 사용하는 경우 부트가 2개 띄워지기 때문에 테스트 실행 속도가 저하되는 문제가 있어서 어제 만든 integrationTest 상속 받아서 테스트 클래스를 사용하는 것이 좋지 않을 까 생각이 들고 링크에서 본 블로그의 경험과 저의 경험이 상충하는 부분이 있어서 해당 블로그 글이 신뢰가 가지는 않는 것 같아요. 컨트롤러 테스트를 진행할 때 mocking 을 사용해서 1차적으로 controller 메서드를 검증하고 추후에 mocking 없는 통합 테스트를 작성해서 전체 서비스 로직의 정합성을 검증하는 식으로 사용을 했었거든요.

**Comment by yudonggeun** [comment]
basetimeentity는 선택적으로 사용하는 것은 좋습니다.

**Comment by zhtmr** [comment]
부트가 2개 띄워진다는 말씀은 webmvctest 와 spring boot test 어노테이션을 한 클래스에서 동시에 사용하셨다는 말씀이신가요? 

보통 컨트롤러 레이어만 테스트할때 @WebMvcTest 만 사용해서 테스트하고 @Service, @Repository 등 다른 bean 들도 필요한 통합테스트시에 @SpringBootTest 를 사용하는걸로 알고있는데.. 만약 컨트롤러만 테스트 시에 @WebMvcTest 를 사용하지 않는다면 컨트롤러 레이어 테스트 시에도 @SpringBootTest 를 써야해서.. 더 느리지않을까 하는데.. 컨트롤러만 테스트할때는 어떤식으로 코드를 작성하셨었나요??
